Repository mre/the-coding-interview, pull requests merged in 2019-12, with the labels that each got.

#130 Added Kotlin solution combine-two-strings
  .editorconfig
  problems/combine-two-strings/combine-two-strings.kts
Labels: Kotlin

#128 Added Bash solution for alphanumeric-string-sort
  problems/alphanumeric-string-sort/alphanumeric-string-sort-test.bash
  problems/alphanumeric-string-sort/alphanumeric-string-sort.bash
Labels: Bash

#129 Added Bash solution for anagram-detection
  problems/anagram-detection/anagram-detection-test.bash
  problems/anagram-detection/anagram-detection.bash
Labels: Bash

#131 Added Kotlin solution factorial
  problems/factorial/factorial.kts
Labels: Kotlin

#114 add remove duplicates from string implementation in Rust
  problems/remove-duplicates-from-string/remove-duplicates-from-string.rs
Labels: Rust

#133 Added Rust factorial solution
  problems/factorial/factorial.rs
Labels: Rust

#132 Added Bash factorial solution
  problems/factorial/README.md
  problems/factorial/factorial.bash
Labels: Bash

#135 Added Test Framework
  .editorconfig
  .gitattributes
  .gitignore
  .jshintrc
  Makefile
  problems/alphanumeric-string-sort/README.md
  problems/alphanumeric-string-sort/alphanumeric-string-sort-test.bash
  problems/alphanumeric-string-sort/alphanumeric-string-sort.cpp
  problems/alphanumeric-string-sort/alphanumeric-string-sort.cs
  problems/alphanumeric-string-sort/alphanumeric-string-sort.go
  problems/alphanumeric-string-sort/alphanumeric-string-sort.kt
  problems/alphanumeric-string-sort/alphanumeric-string-sort.py
  problems/alphanumeric-string-sort/alphanumeric-string-sort.rs
  problems/alphanumeric-string-sort/alphanumeric-string-sort_test.go
  problems/alphanumeric-string-sort/data/001.in
  problems/alphanumeric-string-sort/data/001.out
  problems/alphanumeric-string-sort/data/002.in
  problems/alphanumeric-string-sort/data/002.out
  problems/alphanumeric-string-sort/data/003.in
  problems/alphanumeric-string-sort/data/003.out
  problems/alphanumeric-string-sort/solution.bash
  problems/alphanumeric-string-sort/solution.cpp
  problems/alphanumeric-string-sort/solution.cs
  problems/alphanumeric-string-sort/solution.go
  problems/alphanumeric-string-sort/solution.java
  problems/alphanumeric-string-sort/solution.jl
  problems/alphanumeric-string-sort/solution.js
  problems/alphanumeric-string-sort/solution.kts
  problems/alphanumeric-string-sort/solution.php
  problems/alphanumeric-string-sort/solution.py
  problems/alphanumeric-string-sort/solution.rs
  problems/longest-words/longest-words.c
  test
Labels: enhancement, 🧽 cleanup

#138 Added Advent of Code 2019 Day 1
  problems/advent-of-code/2019/01/01/REAMDE.md
  problems/advent-of-code/2019/01/01/data/001.in
  problems/advent-of-code/2019/01/01/data/001.out
  problems/advent-of-code/2019/01/01/data/002.in
  problems/advent-of-code/2019/01/01/data/002.out
  problems/advent-of-code/2019/01/01/data/003.in
  problems/advent-of-code/2019/01/01/data/003.out
  problems/advent-of-code/2019/01/01/data/004.in
  problems/advent-of-code/2019/01/01/data/004.out
  problems/advent-of-code/2019/01/01/data/005.in
  problems/advent-of-code/2019/01/01/data/005.out
  problems/advent-of-code/2019/01/01/solution.bash
  problems/advent-of-code/2019/01/01/solution.java
  problems/advent-of-code/2019/01/01/solution.js
  problems/advent-of-code/2019/01/01/solution.kts
  problems/advent-of-code/2019/01/01/solution.php
  problems/advent-of-code/2019/01/01/solution.py
  problems/advent-of-code/2019/01/01/solution.rs
  problems/advent-of-code/2019/01/02/README.md
  problems/advent-of-code/2019/01/02/data/001.in
  problems/advent-of-code/2019/01/02/data/001.out
  problems/advent-of-code/2019/01/02/data/002.in
  problems/advent-of-code/2019/01/02/data/002.out
  problems/advent-of-code/2019/01/02/data/003.in
  problems/advent-of-code/2019/01/02/data/003.out
  problems/advent-of-code/2019/01/02/data/004.in
  problems/advent-of-code/2019/01/02/data/004.out
  problems/advent-of-code/2019/01/02/solution.bash
  problems/advent-of-code/2019/01/02/solution.java
  problems/advent-of-code/2019/01/02/solution.js
  problems/advent-of-code/2019/01/02/solution.kts
  problems/advent-of-code/2019/01/02/solution.php
  problems/advent-of-code/2019/01/02/solution.py
  problems/advent-of-code/2019/01/02/solution.rs
Labels: Bash, Java, JavaScript, Kotlin, PHP, Python, Rust, 🎄 AoC

#139 adding missing scenario
  problems/balanced-brackets/balanced-brackets.go
Labels: Go

#112 Added Rust debounce solution
  problems/debounce/debounce.rs
Labels: Rust

#119 C++ solution for Anagram Detection
  problems/anagram-detection/anagram-detection.cpp
Labels: C++

#141 Overhauled Atbash
  Makefile
  problems/atbash/README.md
  problems/atbash/atbash.cs
  problems/atbash/atbash.go
  problems/atbash/atbash.js
  problems/atbash/atbash.kt
  problems/atbash/atbash.php
  problems/atbash/atbash.py
  problems/atbash/atbash.rs
  problems/atbash/atbash.ts
  problems/atbash/data/001.in
  problems/atbash/data/001.out
  problems/atbash/solution.bash
  problems/atbash/solution.c
  problems/atbash/solution.cpp
  problems/atbash/solution.cs
  problems/atbash/solution.dart
  problems/atbash/solution.go
  problems/atbash/solution.java
  problems/atbash/solution.jl
  problems/atbash/solution.js
  problems/atbash/solution.kts
  problems/atbash/solution.php
  problems/atbash/solution.py
  problems/atbash/solution.rb
  problems/atbash/solution.rs
  problems/atbash/solution.scala
  test
Labels: 🧽 cleanup

#140 Added Advent of Code 2019 Day 2
  problems/advent-of-code/2019/02/01/README.md
  problems/advent-of-code/2019/02/01/data/001.in
  problems/advent-of-code/2019/02/01/data/001.out
  problems/advent-of-code/2019/02/01/data/002.in
  problems/advent-of-code/2019/02/01/data/002.out
  problems/advent-of-code/2019/02/01/data/003.in
  problems/advent-of-code/2019/02/01/data/003.out
  problems/advent-of-code/2019/02/01/data/004.in
  problems/advent-of-code/2019/02/01/data/004.out
  problems/advent-of-code/2019/02/01/data/005.in
  problems/advent-of-code/2019/02/01/data/005.out
  problems/advent-of-code/2019/02/01/solution.bash
  problems/advent-of-code/2019/02/01/solution.java
  problems/advent-of-code/2019/02/01/solution.js
  problems/advent-of-code/2019/02/01/solution.kts
  problems/advent-of-code/2019/02/01/solution.php
  problems/advent-of-code/2019/02/01/solution.rs
  problems/advent-of-code/2019/02/02/README.md
  problems/advent-of-code/2019/02/02/data/001.in
  problems/advent-of-code/2019/02/02/data/001.out
  problems/advent-of-code/2019/02/02/solution.bash
  problems/advent-of-code/2019/02/02/solution.java
  problems/advent-of-code/2019/02/02/solution.js
  problems/advent-of-code/2019/02/02/solution.kts
  problems/advent-of-code/2019/02/02/solution.php
  problems/advent-of-code/2019/02/02/solution.rs
Labels: Bash, Java, JavaScript, Kotlin, PHP, Rust, 🎄 AoC

#125 Added Code Jam 2019 #2
  problems/codejam/2019/quali/You-Can-Go-Your-Own-Way/README.md
  problems/codejam/2019/quali/You-Can-Go-Your-Own-Way/Solution.java
Labels: Java, 💾 Code Jam

#143 Overhauled array-pair-sum
  README.md
  problems/array-pair-sum/README.md
  problems/array-pair-sum/array-pair-sum.coffee
  problems/array-pair-sum/array-pair-sum.go
  problems/array-pair-sum/array-pair-sum.java
  problems/array-pair-sum/array-pair-sum.js
  problems/array-pair-sum/array-pair-sum.kt
  problems/array-pair-sum/array-pair-sum.php
  problems/array-pair-sum/array-pair-sum.py
  problems/array-pair-sum/array_pair_sum.cs
  problems/array-pair-sum/array_pair_sum.rs
  problems/array-pair-sum/data/001.in
  problems/array-pair-sum/data/001.out
  problems/array-pair-sum/data/002.in
  problems/array-pair-sum/data/002.out
  problems/array-pair-sum/solution.bash
  problems/array-pair-sum/solution.cs
  problems/array-pair-sum/solution.dart
  problems/array-pair-sum/solution.go
  problems/array-pair-sum/solution.java
  problems/array-pair-sum/solution.js
  problems/array-pair-sum/solution.kts
  problems/array-pair-sum/solution.php
  problems/array-pair-sum/solution.py
  problems/array-pair-sum/solution.rs
Labels: 🧽 cleanup
